version: '3'
services:
  nginx:
      image: nginx:latest
      ports:
        - 9011:80
      volumes:
        - ./config/nginx:/etc/nginx/conf.d
        - ./src/static:/elevator_system/static
      depends_on:
        - web
  web:
    build: .
    command: ["./start.sh"]
    volumes:
      - .:/elevator_system
      - /var/log/elevator_system:/var/log/elevator_system
    expose:
      - 9011