# Generated by Django 4.2.3 on 2023-07-26 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElevatorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='elevator',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator_management.elevatorstatus'),
        ),
    ]
